### ISSUE TITLE
Introduce new geometry error.

### ISSUE THREAD

**Issue by bekoyim** [ladybug-tools/butterfly#258] opened 2017-07-28 05:01 UTC
I downloaded and ran the example file for outdoor airflow. Everything works fine. However once I try to replace the existing geometry with a new geometry I created in Rhino, and re-run the script, the result gets funky. All I did was replacing the brep component.
![capture1](https://user-images.githubusercontent.com/30517355/28703148-a6427fce-7394-11e7-8e50-54fe5c49c5e0.PNG)

**Comment by grifang** [comment] 2017-07-29 00:07
I've got the same issue yesterday...pls let me know in case you find a solution..I'll do the same...

**Comment by Zarisu** [comment] 2017-07-29 10:27
I'm guessing that this is caused by the selected test points (probes), which are not correct if only you have only change the geometry.

Solution: Add a new surface to the 'genTestPts' component.

Explanation: If you use the default geometry the surface has the geometries subtracted from it. However, if you only change the geometries, the surface of investigation is considering the test points within your geometry, which is what causes the weird numbers. 

Hope this is written in an understandable way, otherwise please let me know :)

**Comment by grifang** [comment] 2017-07-29 11:55
Hi Zarisu

Thank you for your answer

 I used as new brep for my test a surface achieved with the projection of the wind tunnel box split with the base polylines of the buildings.... unfortunately the result is the same.

I tried to apply a cull pattern to the results in order to identify the "tricky" values and the corresponding faces on the test mesh.

They're along the building boundaries.

Hope that this could be helpful for someone that know this plug-in better than me.

Cheers
![capture](https://user-images.githubusercontent.com/30264796/28744648-36ed0bde-745d-11e7-9043-7b7aa4d8f414.JPG)

**Comment by Zarisu** [comment] 2017-07-29 14:49
Hi @grifang,
This might not be the issue but I would like to know whether all your test points are calculated before suggesting other solutions. 
You can see if this is the case in the file 'C:\Users\YourUserName\butterfly\YourCaseName\log\simpleFoam.txt'. Where the file would tell you if any of the test points (probes) are missing. It will be written before the first iteration is run (Time = 1).
Does your simulation consider all points?

**Comment by grifang** [comment] 2017-07-29 16:28
No it doesn't....

![capture1](https://user-images.githubusercontent.com/30264796/28746377-38bde502-7483-11e7-9510-2db82a71715a.JPG)

**Comment by Zarisu** [comment] 2017-07-31 10:11
Hi @grifang,
Sorry for the late reply. It means that some of your probes (test points) are outside the mesh and therefore not considered when simulating. The picture below illustrates your problem. I recommend that you use paraview to check your mesh :) Best Regards Zarisu
![cilindro_close_rightblock_](https://user-images.githubusercontent.com/23387793/28773303-43170e0e-75e9-11e7-8f74-9e94ad3e44e4.png)

**Comment by amirtabadkani** [comment] 2017-07-31 10:21
Hi @Zarisu 

Actually I have the same error when I change the model and I double checked the test points ,, but still is the same.. 
![canvas at 18 03 39](https://user-images.githubusercontent.com/17779829/28773674-c6c8b0fc-75ff-11e7-81c0-7ab1a2027b96.png)

**Comment by grifang** [comment] 2017-07-31 10:44
Thank you for the answer now I understand the problem....can I kindly ask you if there is a way to be sure that all my points could be all included?I mean is there any basic rule that I'm missing or do I have just to guess?
In the tutorial given for the outdoor flow the test geometries are made in rhino..unfortunately in my case I need to keep them in grasshopper.

**Comment by TheodoreGalanos** [comment] 2017-07-31 11:44
Hi @grifang 

A rule of thumb would be that you offset your points from any closed volumes (e.g. buildings) by at least half the background mesh size (i.e. blockMesh cell size) in the region you want to assess. I think that would eliminate this issue. If that seems a bit high to you in some cases and would take away a lof of area from your assessment then I think you could consider increasing mesh quality by reducing the background mesh.

Another quick way of doing the above, but might not necessarily accomplish what you want, is to cull all probe values above a certain high threshold (e.g. 10000). That should allow you to visualise the remaining points which were inside the mesh to begin with.

Hope this helps.

Kind regards,
Theodore.

**Comment by grifang** [comment] 2017-07-31 14:16
@TheodoreGalanos  
@Zarisu 

Solved!!!

I had 2 main issues:

1)The first try showed a wrong meshing with triangles.
I don't know why but recomputing the whole script it solves the problem

2) the mesh built with the test geometry is still with triangular faces along the buildings.
I had to cull several faces along the volumes with a tolerance of 1 m (or a sufficient one for the simulation), the same for the probes points.

Thank you very much!

![capture3](https://user-images.githubusercontent.com/30264796/28781774-1733de06-7603-11e7-9b33-f1fe4e96b8f4.JPG)

**Comment by TheodoreGalanos** [comment] 2017-08-01 03:52
@grifang Good to hear, glad it worked!

Seeing the picture it is easy to realize this is a meshing quality issue. Notice how the building on the left doesn't appear to have this issue. This is because it is orthogonal to the backround mesh so snapping is easy. The one on the right looks as if snapping didn't happen (it looks like a blockMesh literally, you can get that if you run SHM with snap false). If you would decrease the background mesh and allow for a few more refinement levels on the building this issue would drastically reduce.

Kind regards,
Theodore.

**Comment by mostaphaRoudsari** [comment] 2017-08-24 18:27
Thank you @Zarisu and @TheodoreGalanos for helping with this issue. I think it's worthwhile to add this check into Butterfly itself. I had the check originally but it adds extra checks during the run. Is there a way to check if any probe is not valid before running the solver?

I close this issue as the original problem is solved.

**Closed by mostaphaRoudsari** 2017-08-24 18:27 UTC
